name: Forge Mod CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:
    inputs:
      skip_tests:
        description: 'Skip test execution'
        required: false
        default: false
        type: boolean

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Xmx2g"

jobs:
  build:
    name: Build (${{ matrix.os }}, Java ${{ matrix.java }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: [17]
        include:
          - os: ubuntu-latest
            java: 17
            java-home: /usr/lib/jvm/temurin-17-jdk-amd64
          - os: windows-latest
            java: 17
            java-home: C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\17.0.8+8\x64

    steps:
    # 步骤1：检出代码
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 步骤2：设置Java环境
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: 'gradle'
        check-latest: true

    # 步骤3：验证Java路径
    - name: Verify Java Installation
      shell: bash
      run: |
        JAVA_HOME=${{ matrix.java-home }}
        echo "JAVA_HOME: $JAVA_HOME"
        if [ ! -d "$JAVA_HOME" ]; then
          echo "::error::Java home directory not found: $JAVA_HOME"
          exit 1
        fi
        "$JAVA_HOME/bin/java" -version

    # 步骤4：配置Gradle
    - name: Configure Gradle
      shell: bash
      run: |
        sed -i '/org.gradle.java.home/d' gradle.properties || true
        echo "org.gradle.java.home=${{ matrix.java-home }}" >> gradle.properties

    # 步骤5：执行构建
    - name: Run Gradle build
      shell: bash
      run: |
        ./gradlew build \
          --no-daemon \
          --stacktrace \
          --info \
          ${{ inputs.skip_tests && '-x test' || '' }}

    # 步骤6：上传产物
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: mod-${{ runner.os }}
        path: build/libs/*.jar
