name: Java CI with Linux Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Xmx2g"

jobs:
  build:
    name: Build with Java 17 (Linux)
    runs-on: ubuntu-latest
    
    steps:
    # 步骤1：检出代码
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 步骤2：设置Java环境（使用Temurin发行版）
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
        check-latest: true

    # 步骤3：动态配置Gradle Java路径（关键修复点）
    - name: Configure Gradle Java Home
      run: |
        echo "org.gradle.java.home=$JAVA_HOME" >> gradle.properties
        echo "Configured Gradle Java Home: $JAVA_HOME"

    # 步骤4：配置Gradle缓存
    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # 步骤5：确保gradlew可执行
    - name: Make gradlew executable
      run: chmod +x gradlew

    # 步骤6：执行构建
    - name: Run Gradle build
      run: |
        ./gradlew build \
          --no-daemon \
          --stacktrace \
          --info

    # 步骤7：上传构建产物
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: java-build-artifacts
        path: |
          build/libs/*.jar
          build/reports/**
        if-no-files-found: error
        retention-days: 7
